# Generated by Django 3.1.5 on 2021-01-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalUrl', models.CharField(max_length=200)),
                ('shortnedUrl', models.SlugField(blank=True, max_length=6, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
